/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
/*  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
*/
  // But you can create a sidebar manually

  docs: [
    'intro', // Directly set the doc ID to refer to the doc. Omit the file name suffix such as .md.
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
      },
      items: [
        'introduction/graph',
        'introduction/graph-database',
        'introduction/related-tech',
        'introduction/what-is-nebula-graph',
        {
          type: 'category',
          label: 'NebulaGraph Architecture',
          link: {
            type: 'generated-index',
          },
          items: [
            'introduction/nebula-graph-architecture/architecture-overview',
            'introduction/nebula-graph-architecture/meta-service',
            'introduction/nebula-graph-architecture/graph-service',
            'introduction/nebula-graph-architecture/storage-service',
          ],
        },
        'introduction/data-model',
        'introduction/path',
        'introduction/vid',
      ],
    },
  ],

};

module.exports = sidebars;
